### ISSUE TITLE
Could you convert DP to EDP ?

### ISSUE THREAD

**Issue by fanksy** [Ausdauersportler/IMAC-EFI-BOOT-SCREEN#2]
Hi, I apprecicate you much for your work, the RX5500XT-EnableGop.rom worked on my laptop, but the screen is recognized external display, I can not adjust brightness.

**Comment by Ausdauersportler** [comment]
No I cannot - nobody can modify a RX5500XT vBIOS. Therefore the OpenCore injection method only usable with macOS has been used.

**Comment by fanksy** [comment]
oh, i see it, thanks

> No I cannot - nobody can modify a RX5500XT vBIOS. Therefore the OpenCore injection method only usable with macOS has been chosen as described in the [wiki](https://github.com/Ausdauersportler/IMAC-EFI-BOOT-SCREEN/wiki/ObjectInfoNavi) in more detail.
